name: Push Events
on:
  push:
    branches:
      - main
      - dev
      - test
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
    - name: Information
      run: |
        echo "This is a push event call"
