name: Issue Translator
on: 
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  issue-translator:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v4
      - uses: tomsun28/issues-translate-action@v2.7
    
